add inframap generator script & s3 bucket object and rules
toluna-terraform/terraform-aws-pipeline-controller pull request #27
Opened 2023-02-13 12:27 UTC by msaaditoluna

2023-02-15 13:20 UTC, Eli-Meitner approved these changes

2023-03-16 13:48 UTC, evgenygigi commented on scripts/generator.sh
> +wget -qO- https://github.com/cycloidio/inframap/releases/download/v0.6.7/inframap-linux-amd64.tar.gz | tar xvz
is it ok for the version to be hardcoded here?

2023-03-16 13:55 UTC, raanan245 requested changes

2023-03-16 13:55 UTC, raanan245 commented on scripts/generator.sh
> +wget -qO- https://github.com/cycloidio/inframap/releases/download/v0.6.7/inframap-linux-amd64.tar.gz | tar xvz
better to have it in our ECR (main account) or in S3 bucket (also in main) with bucket policy to allow access only from our AWS accounts (organization)

2023-03-16 14:18 UTC, closed without merging